@startuml

skin rose
left to right direction
title магазин
actor продавец
actor клиент

rectangle магазин {
клиент -- (покупка товара)
клиент -- (возврат товара)
клиент -- (оформление карты магазина)
клиент -- (списание баллов)
(покупка товара) <.> (возврат товара) : include
(оформление карты магазина) .> (списание баллов) : extend
тестировщик -- (проверка работоспособности мобильного приложения)
}
@enduml