@startuml

skin rose
left to right direction
title текстовый редактор (диаграмма прецедентов) 
actor человек
actor программа
actor принтер

rectangle текстовый_редактор {
человек -- (создать файл)
человек -- (редактировать файл)
человек -- (отправить файл на печать)
принтер -- (печатать файл)
программа -- (подсветить ключевые слова)
(создать файл) .> (редактировать файл) : extend
(создать файл) .> (отправить файл на печать) : extend
(печатать файл) ..> (отправить файл на печать):<<include>>
(подсветить ключевые слова) ..> (создать файл):<<include>>
}
@enduml
