@startuml

skin rose
left to right direction
title текстовый редактор (диаграмма прецедентов) 
actor человек
actor программа
actor принтер

rectangle текстовый_редактор {
человек -- (создать файл)
человек -- (редактировать файл)
человек -- (отправить файл на печать)
принтер -- (печатать файл)
программа -- (подсветить ключевые слова)
(создать файл) .> (редактировать файл) : extend
(создать файл) .> (отправить файл на печать) : extend
(печатать файл) ..> (отправить файл на печать):<<include>>
(подсветить ключевые слова) ..> (создать файл):<<include>>
}
@enduml


@startuml
title текстовый редактор (диаграмма классов) 
class Файл{
+Текст
}
class Файл_спец_формата{
+Текст
+Ключевые слова
}
class Пользователь{
+Имя
Предоставлять файл()
}

class Программное_обеспечение{
+исполняемый код
+подаваемые на вход файлы
}

Файл_спец_формата --> Файл
Пользователь ..> Файл: выбирает
Файл ..> Программное_обеспечение: подаётся на вход

@enduml 