@startuml "Практическая работа 2"
title Текстовый редактор (диаграмма последовательности)
skinparam backgroundcolor SkyBlue
participant Пользователь
participant Панель_инструментов
participant Меню
participant Область_редактирования
activate Пользователь
Пользователь -> Меню: Создать
activate Меню
Меню -> Область_редактирования: Отображает область
deactivate Меню
activate Область_редактирования
Пользователь -> Область_редактирования: Редактирует файл
Пользователь -> Панель_инструментов: Использует инструменты редактирования
activate Панель_инструментов
Панель_инструментов -> Область_редактирования: Изменяет текст
deactivate Панель_инструментов
Пользователь -> Меню: Сохранить
deactivate Пользователь
activate Меню
deactivate Панель_инструментов
Меню -> Область_редактирования: Закрывает область
deactivate Меню
deactivate Область_редактирования
@enduml

